### ISSUE TITLE
Error with clean install in island.schem

### ISSUE THREAD

**Issue by tastybento** [BentoBoxWorld/CaveBlock#12]
#### Description
CaveBlock throws error on a fresh install when loading the island.schem file.

```
[21:03:24 INFO]: [BentoBox] Loading island.schem for CaveBlock-world
[21:03:24 ERROR]: Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.IllegalArgumentException: Material cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:69) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:57) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:479) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:81) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:121) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:199) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at world.bentobox.bentobox.schems.Clipboard.load(Clipboard.java:625) ~[?:?]
	at world.bentobox.bentobox.managers.SchemsManager.loadSchem(SchemsManager.java:115) ~[?:?]
	at world.bentobox.bentobox.managers.SchemsManager.lambda$loadIslands$3(SchemsManager.java:96) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_181]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_181]
	at world.bentobox.bentobox.managers.SchemsManager.loadIslands(SchemsManager.java:95) ~[?:?]
	at world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:118) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_181]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_181]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) [?:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) [?:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) [?:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_181]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_181]
	at world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:64) [bentobox-1.3.0-SNAPSHOT.jar:?]
	at world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:150) [bentobox-1.3.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:809) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.Bukkit.reload(Bukkit.java:574) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:689) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-b0f4c22-d5e9688]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[21:03:24 INFO]: [BentoBox] Loading nether-island.schem for CaveBlock-world_nether
[21:03:24 INFO]: [BentoBox] Loading end-island.schem for CaveBlock-world_the_end
```

####  Steps to reproduce the behavior:
1. Fresh install with BentoBox and CaveBlock
2. Start server
3. See error

#### Expected behavior
Load without errors.

#### Server Information:
[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): JSON
 - OS: [e.g. iOS] - MacOS
 - Java Version: [e.g. Java 8] - Java 8
 - BentoBox version: [e.g. 1.7.2.21] 1.3.0
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
[21:06:54 INFO]: BentoBox version: 1.3.0-SNAPSHOT
[21:06:54 INFO]: Loaded Game Worlds:
[21:06:54 INFO]: CaveBlock-world (CaveBlock)
[21:06:54 INFO]: Loaded Addons:
[21:06:54 INFO]: CaveBlock 0.1.0
[21:06:54 INFO]: Level 1.2.1-SNAPSHOT
[21:06:54 INFO]: Biomes 0.5.0-SNAPSHOT
[21:06:54 INFO]: WelcomeWarps 1.2-SNAPSHOT
[21:06:54 INFO]: Challenges 0.5.0-SNAPSHOT
 - Other plugins? [Do '/plugins' and copy/paste from the console]
Essentials, PlaceholderAPI, BentoBox

####  Additional context
Looks like an error in the island.schem file.

**Comment by tastybento** [comment]
The BEETROOT_SEEDS was not updated into the .schem file.
