### ISSUE TITLE
Caveblock 1.14.0 not creating island nor resetting old caveblock 1.13 islands

### ISSUE THREAD

**Issue by frigid97** [BentoBoxWorld/CaveBlock#49]
#### Describe the bug
Caveblock not creating island nor resetting existing islands when trying /cave reset

Just using the plugin after replacing 1.13 or on a new server it just wouldn't reset or make a new caveblock, and this error appears on the console, fresh server and old server.
![unknown png2](https://user-images.githubusercontent.com/68096869/87119888-cd71ab00-c2b1-11ea-9bca-84b8041a863a.png)
![unknown](https://user-images.githubusercontent.com/68096869/87119894-ce0a4180-c2b1-11ea-8cfc-c0b780b0e555.png)

#### Expected behavior
The previous version still works.

**Comment by tastybento** [comment]
Weird. The blueprint bundles have names in them instead of filenames. This is what the default json file should look like:

```
{
  "uniqueId": "default",
  "icon": "STONE",
  "displayName": "&eThe Default CaveBlock",
  "description": [
    "Default Cave"
  ],
  "requirePermission": false,
  "blueprints": {
    "NORMAL": "cave",
    "NETHER": "nether-cave",
    "THE_END": "end-cave"
  },
  "slot": 0
}```

This is what it looks like in the repo:

```
{
  "uniqueId": "default",
  "icon": "STONE",
  "displayName": "&eThe Default CaveBlock",
  "description": [
    "Default Cave"
  ],
  "requirePermission": false,
  "blueprints": {
    "NORMAL": "the cave",
    "NETHER": "the nether cave",
    "THE_END": "the end cave"
  },
  "slot": 0
}
```
I'm uploading a fix, but I want to find out the root cause. Maybe it's the Blueprint editor GUI?

Also, these files have been like this for 10 months.

**Comment by tastybento** [comment]
I pushed a new version to master because right now the download doesn't work at all.

**Comment by frigid97** [comment]
[17:47:43 ERROR]: Could not pass event IslandPreclearEvent to BentoBox v1.14.0
java.lang.NullPointerException: null
        at world.bentobox.level.objects.LevelsData.remove(LevelsData.java:169) ~[?:?]
        at world.bentobox.level.LevelsManager.removeEntry(LevelsManager.java:401) ~[?:?]
        at world.bentobox.level.listeners.IslandActivitiesListeners.remove(IslandActivitiesListeners.java:73) ~[?:?]
        at world.bentobox.level.listeners.IslandActivitiesListeners.onIslandDelete(IslandActivitiesListeners.java:68) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor359.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-79]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-79]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-79]        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-79]
        at world.bentobox.bentobox.api.events.island.IslandEvent$IslandEventBuilder.build(IslandEvent.java:747) ~[?:?]
        at world.bentobox.bentobox.api.commands.island.IslandResetCommand.resetIsland(IslandResetCommand.java:129) ~[?:?]
        at world.bentobox.bentobox.api.commands.island.IslandResetCommand.execute(IslandResetCommand.java:92) ~[?:?]
        at world.bentobox.bentobox.panels.IslandCreationPanel.lambda$openPanel$2(IslandCreationPanel.java:55) ~[?:?]
        at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:56) ~[?:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_251]
        at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:54) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor405.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-79]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-79]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-79]        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-79]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2421) ~[patched_1.16.1.jar:git-Paper-79]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.1.jar:git-Paper-79]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.1.jar:git-Paper-79]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-79]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-79]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-79]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-79]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-79]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-79]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-79]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.1.jar:git-Paper-79]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1259) ~[patched_1.16.1.jar:git-Paper-79]        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-79]        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-79]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[17:47:43 ERROR]: [BentoBox] Blueprint bundle has no normal world blueprint, using default
[17:47:43 ERROR]: [BentoBox] NO DEFAULT BLUEPRINT FOUND! Make sure 'island.blu' exists!

**Comment by tastybento** [comment]
@frigid97 assuming you haven't customized any blueprints, delete the cable block blueprint folder and reboot. Alternatively, do `/cba bp` and set a blueprint for each missing world.

**Comment by frigid97** [comment]
Yes, deleting the blueprint folder worked, thanks.
