### ISSUE TITLE
[Server thread/ERROR]: [BentoBox] Plugin BentoBox v1.15.3 has failed

### ISSUE THREAD

**Issue by RexEtImperator** [BentoBoxWorld/CaveBlock#53]
1.when reloading plugin
[Server thread/ERROR]: [BentoBox] Plugin BentoBox v1.15.3 has failed to register events for class world.bentobox.upgrades.listeners.IslandChangeListener because world/bentobox/limits/events/LimitsJoinPermCheckEvent does not exist.

2. sometimes in cmd
[BentoBox] Plugin BentoBox v1.15.3 generated an exception while executing task 1702
java.lang.NullPointerException: null
	at world.bentobox.challenges.web.WebManager.requestCatalogGitHubData(WebManager.java:67) ~[?:?]
	at world.bentobox.challenges.web.WebManager.lambda$new$1(WebManager.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-800b93f-8160e29]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

3. challenge command for admin (commands for players not working)
org.bukkit.command.CommandException: Unhandled exception executing 'gadmin challenges' in world.bentobox.caveblock.CaveBlock$2(gadmin)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot.jar:git-Spigot-800b93f-8160e29]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at world.bentobox.challenges.web.WebManager.isEnabled(WebManager.java:207) ~[?:?]
	at world.bentobox.challenges.panel.admin.AdminGUI.createButton(AdminGUI.java:572) ~[?:?]
	at world.bentobox.challenges.panel.admin.AdminGUI.build(AdminGUI.java:151) ~[?:?]
	at world.bentobox.challenges.commands.admin.Challenges.execute(Challenges.java:62) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:266) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:239) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	... 16 more

4. on loading and /bbox reload
[BentoBox] Error in YML file: NETHER_WASTES is not a valid value in the enum org.bukkit.block.Biome!

##### Output of `/bbox version` (Mandatory)

[Server thread/INFO]: Serwer dzia┼éa na SPIGOT 1.15.2.
[14:57:13] [Server thread/INFO]: Wersja BentoBoxa: 1.15.3
[14:57:13] [Server thread/INFO]: Baza danych: JSON
[14:57:13] [Server thread/INFO]: Wczytane ┼Ťwiaty gry:
[14:57:13] [Server thread/INFO]: caveblock-world (CaveBlock): ┼Üwiat wysp, Nether, End
[14:57:13] [Server thread/INFO]: Wczytane dodatki:
[14:57:13] [Server thread/INFO]: Border 2.0.0 (ENABLED)
[14:57:13] [Server thread/INFO]: CaveBlock 1.14.1 (ENABLED)
[14:57:13] [Server thread/INFO]: Challenges 0.8.3 (ENABLED) <--- not working too
[14:57:13] [Server thread/INFO]: ControlPanel 1.7.0 (ENABLED)
[14:57:13] [Server thread/INFO]: Level 2.5.0 (ENABLED)
[14:57:13] [Server thread/INFO]: Upgrades 0.2.0-SNAPSHOT-b76 (ENABLED)

**Comment by BONNe** [comment]
This crash happens because you have a different crash at server startup. 

It is just weird that after a 1 year I have reported this issue, @tastybento or @Poslovitch haven't introduced a system, that disables bentobox, if it crashes in the last task in a startup.

**Comment by tastybento** [comment]
What is happening here?

**Comment by BONNe** [comment]
This is the original report about the issue: https://github.com/BentoBoxWorld/BentoBox/issues/1281

**Comment by tastybento** [comment]
Fixed by BentoBoxWorld/BentoBox#1281
