### ISSUE TITLE
1.18 Biomes Conflict 

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/CaveBlock#69]
### Expected behavior

I was expecting the plugin to work properly.

### Observed/Actual behavior

```
[09:43:12] [Server thread/ERROR]: [BentoBox] Could not load config object! null
[09:43:12] [Server thread/ERROR]: [BentoBox] java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at BentoBox-1.19.0.jar//world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.createObject(YamlDatabaseHandler.java:152)
	at BentoBox-1.19.0.jar//world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.loadObject(YamlDatabaseHandler.java:95)
	at BentoBox-1.19.0.jar//world.bentobox.bentobox.api.configuration.Config.loadConfigObject(Config.java:64)
	at BentoBox-1.19.0.jar//world.bentobox.bentobox.api.configuration.Config.loadConfigObject(Config.java:81)
	at world.bentobox.caveblock.CaveBlock.loadSettings(CaveBlock.java:98)
	at world.bentobox.caveblock.CaveBlock.onLoad(CaveBlock.java:35)
	at BentoBox-1.19.0.jar//world.bentobox.bentobox.managers.AddonsManager.initializeAddon(AddonsManager.java:222)
	at BentoBox-1.19.0.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:195)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at BentoBox-1.19.0.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:138)
	at BentoBox-1.19.0.jar//world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:164)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563)
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:319)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1215)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchFieldError: MOUNTAINS
	at world.bentobox.caveblock.Settings.<init>(Settings.java:2181)
	... 33 more

[09:43:12] [Server thread/ERROR]: [BentoBox] [CaveBlock] CaveBlock settings could not load! Addon disabled.
[09:43:12] [Server thread/ERROR]: [BentoBox] Skipping CaveBlock due to an unhandled exception...
[09:43:12] [Server thread/ERROR]: [BentoBox] java.lang.NullPointerException: Cannot invoke "world.bentobox.caveblock.Settings.getNormalBlocks()" because the return value of "world.bentobox.caveblock.CaveBlock.getSettings()" is null
	at world.bentobox.caveblock.generators.populators.MaterialPopulator.loadSettings(MaterialPopulator.java:46)
	at world.bentobox.caveblock.generators.populators.MaterialPopulator.<init>(MaterialPopulator.java:35)
	at world.bentobox.caveblock.generators.ChunkGeneratorWorld.reload(ChunkGeneratorWorld.java:227)
	at world.bentobox.caveblock.generators.ChunkGeneratorWorld.<init>(ChunkGeneratorWorld.java:41)
	at world.bentobox.caveblock.CaveBlock.onLoad(CaveBlock.java:37)
	at BentoBox-1.19.0.jar//world.bentobox.bentobox.managers.AddonsManager.initializeAddon(AddonsManager.java:222)
	at BentoBox-1.19.0.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:195)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at BentoBox-1.19.0.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:138)
	at BentoBox-1.19.0.jar//world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:164)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563)
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:319)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1215)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps/models to reproduce

The problem is that it gives an error because there is no biome named "MOUNTAINS" anymore, but I changed the "default-biome" setting in "config.yml" to "LUSH_CAVES".

But the error persists.

I think it needs the 1.18 biome update.

### BentoBox version

![image](https://user-images.githubusercontent.com/47111280/145765489-9d5e296b-cd8e-4ebd-9dbb-29d7892c3534.png)

**Comment by BONNe** [comment]
This issue is fixed in 1.15 version.
